require: rubocop-rspec
Metrics/LineLength:
  Max: 150
Metrics/CyclomaticComplexity:
  Max: 10
AllCops:
  RunRailsCops: true
  Exclude:
    - 'db/**/*'
    - 'config/**/*'
    - 'script/**/*'
    - 'bin/**/*'
    - 'vendor/**/*'
Documentation:
  Enabled: false

RSpec/ExampleWording:
  Enabled: false