base: &base
  access_key_id: AKIAIJKNKE7VZNMLW3VQ
  secret_access_key: 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
  #  distribution_domain: XXXX.cloudfront.net
  options:
    use_ssl: true
    persistent: false

production:
  bucket_name: brandscopic-prod
  <<: *base

staging:
  bucket_name: brandscopic-stage
  <<: *base

demo:
  bucket_name: brandscopic-demo
  <<: *base

development:
  bucket_name: brandscopic-dev
  <<: *base

test:
  bucket_name: brandscopic-test
  <<: *base