events:
  - Campaign
  - Brand
  - Area
  - CompanyUser
  - Team

event_data:
  - Campaign
  - Brand
  - Area
  - CompanyUser
  - Team

photos:
  - Campaign
  - Brand
  - Area
  - CompanyUser
  - Team

activities:
  - Campaign
  - Brand
  - Area
  - CompanyUser
  - Team

results_comments:
  - Campaign
  - Brand
  - Area
  - CompanyUser
  - Team

results_expenses:
  - Campaign
  - Brand
  - Area
  - CompanyUser
  - Team

results_photos:
  - Campaign
  - Brand
  - Area
  - CompanyUser
  - Team

surveys:
  - Campaign
  - Brand
  - Area
  - CompanyUser
  - Team

tasks:
  - Campaign

venues:
  - Campaign
  - Brand
  - Area

visits:
  - Campaign
  - Brand
  - Area
  - class: Place
    label: 'Cities'
  - class: CompanyUser
    label: 'Brand Ambassadors'

teams:
  - Campaign

company_users:
  - Team
  - Campaign
  - Role

company_users:
  - Campaign

campaigns:
  - Brand
  - BrandPortfolio
  - CompanyUser
  - Team

brand_portfolios:
  - Brand