filters:
  events:
    campaigns: [Campaign]
    brands: [Brand, BrandPortfolio]
    areas: [Area]
    people: [CompanyUser, Team]
    event_status:
      items: [Submitted, Late, Due, Approved, Rejected]
      name: 'event_status'
    active_state:
      items: [Active, Inactive]
      name: 'status'
  venues:
    sliders: 
      method: venues_sliders
    price:
      items: [[1, '$'], [2, '$$'], [3, '$$$'], [4, '$$$$']]
      name: 'event_status'
    areas: [Area]
    campaigns: [Campaign]
    brands: [Brand]
  campaigns:
    brands: [Brand]
    brand_portfolios: [BrandPortfolio]
    people: [CompanyUser, Team]
    active_state:
      items: [Active, Inactive]
      name: 'status'
  brands:
    active_state:
      items: [Active, Inactive]
      name: 'status'
  company_users:
    roles: [Role]
    campaigns: [Campaign]
    teams: [Team]
    active_state:
      items: [Active, Inactive]
      name: 'status'
  teams:
    campaigns: [Campaign]
    active_state:
      items: [Active, Inactive]
      name: 'status'
  roles:
    active_state:
      items: [Active, Inactive]
      name: 'status'
  activity_types:
    active_state:
      items: [Active, Inactive]
      name: 'status'
  areas:
    active_state:
      items: [Active, Inactive]
      name: 'status'
  brand_portfolios:
    brands: [Brand]
    active_state:
      items: [Active, Inactive]
      name: 'status'
  date_ranges:
    active_state:
      items: [Active, Inactive]
      name: 'status'
  day_parts:
    active_state:
      items: [Active, Inactive]
      name: 'status'
  brand_ambassadors/visits:
    brand_ambassadors:
      method: brand_ambassadors_bucket
    campaigns: [Campaign]
    areas: [Area]
    cities: 
      method: cities_bucket
  activities:
    activity_types: [ActivityType]
    brands: [Brand]
    campaigns: [Campaign]
    areas: [Area]
    users: [CompanyUser]
    active_state:
      items: [Active, Inactive]
      name: 'status'
  results_photos:
    campaigns: [Campaign]
    brands: [Brand]
    areas: [Area]
    active_state:
      items: [Active, Inactive]
      name: 'status'