production:
  solr:
    hostname: 127.0.0.1
    port: 8983
    log_level: WARNING
    path: /solr/production
    read_timeout: 10
    open_timeout: 10
  auto_commit_after_request: true
  auto_commit_after_delete_request: true

development:
  solr:
    hostname: 127.0.0.1
    port: 8982
    log_level: INFO
    path: /solr/development
  auto_commit_after_request: true
  auto_commit_after_delete_request: true

test:
  solr:
    hostname: localhost
    port: <%= 8981 + ENV['TEST_ENV_NUMBER'].to_i %>
    log_level: WARNING
    data_path: <%= File.join(::Rails.root, 'solr', 'data', ::Rails.env, ENV['TEST_ENV_NUMBER'].to_i.to_s) %>
    log_file: <%= File.join(::Rails.root, 'log', "sunspot-solr-test-#{ENV['TEST_ENV_NUMBER'].to_i}.log") %>
    pid_path: <%= File.join(::Rails.root, 'solr', 'pids', ::Rails.env, "#{ENV['TEST_ENV_NUMBER'].to_i}") %>